### PR TITLE
Fix unreachable code in file creation

### PR DESCRIPTION
**Pull request by Writhe**
This PR aims to improve error handling for failed signature file creation. As I mentioned [here](https://github.com/cla-assistant/github-action/issues/7#issuecomment-590331638), the code responsible for handling the failed pair of promises is unreachable in the current master branch. Additionally, there is an unhandled promise rejection which causes node to issue a warning, which - in turn - makes the action output harder to read. The changes proposed here should solve both problems.

Additionally, I have taken the liberty of switching the build process from local TSC and GH-based node workflow to a fully local build step which includes dependency bundling.

Cheers!

### CODE REVIEW

**Comment by ibakshay** [comment]
@Writhe, This is amazing!!. Thank you very much for your submission 😄 . We will soon review this PR..

**Comment by Writhe** [comment]
@ibakshay Sure thing. I wasn't 100% convinced I should interfere with the workflow, to be honest.

Aaaaand I've just realised you have the entire `node_modules` directory included in the repo. For some reason I'd assumed the deps were somehow provided by the CI - my bad. I think they can safely be .gitignored, now.

I'll restore the workflow file, then, but will leave the CI bits to you. My Github-fu is too weak to propose a ready solution, but it would probably make sense to run `ncc` as part of CI, whenever the linting / testing part succeeds. Never tried that on GH, tbh.

**Comment by Writhe** [comment]
I've decided against removing `node_modules` in this PR. I don't even want to know what a diff with over 7000 removed files looks like. 😄

**Comment by ibakshay** [comment]
> I'll restore the workflow file, then, but will leave the CI bits to you. My Github-fu is too weak to propose a ready solution, but it would probably make sense to run `ncc` as part of CI, whenever the linting / testing part succeeds. Never tried that on GH, tbh.

Hi @Writhe, thank you very much :). Your proposal for CI  definitely makes sense, however, test cases are not implemented in this action yet. It is in our backlog and I have also opened an [issue](https://github.com/cla-assistant/github-action/issues/9) for that.

**Comment by ibakshay** [comment]
> Aaaaand I've just realised you have the entire `node_modules` directory included in the repo. For some reason I'd assumed the deps were somehow provided by the CI - my bad. I think they can safely be .gitignored, now.

Yes, you are right :). `node_modules` can be ignored in `.gitignore`. thanks for pointing it out 😄, I didn't notice until now.
> I've decided against removing node_modules in this PR. I don't even want to know what a diff with > >over 7000 removed files looks like. 😄

Haha, I will remove `node_modules` after merging this Pull Request.  Thank you very much once again for your contribution, highly appreciated 🏅.

**Comment by Writhe** [comment]
You're welcome, cheers.

> I didn't notice until now.

I think `node_modules` were un-ignored on purpose several commits ago, to make up for the lack of bundling. It's not a bad idea, but `ncc` seems cleaner. Both approaches are mentioned in Github's official docs.

**Comment by ibakshay** [comment]
> You're welcome, cheers.
> 
> > I didn't notice until now.
> 
> I think `node_modules` were un-ignored on purpose several commits ago, to make up for the lack of bundling. It's not a bad idea, but `ncc` seems cleaner. Both approaches are mentioned in Github's official docs.

Could you please send the link of the GitHub's official docs  ?. I am interested to go through to  it :).

**Comment by Writhe** [comment]
@ibakshay
Of course. [Intro to GH Actions](https://help.github.com/en/actions/building-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github). This specific part mentions `ncc` as an alternative to checking in your `node_modules` dir.

**Pull request merged**
